name: 
# Ensure the workflow runs on schedule (Sunday at 0:00) and on push to the main branch
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0" 

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - name: 'Node env setup'
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install the dependencies
        run:  |
          cd backend
          npm ci

      # Run the tests.
      - name: Run tests
        run: |
          cd backend 
          npm test

      - name: Run linter
        run: cd backend && npm run lint

      - name: Message post completion
        run: |
          echo "Hello ${{github.actor}}. You pushed to ${{github.repository}} at $(date)."


